
# Source: [OpenAI Documentation](https://platform.openai.com/docs/guides/function-calling)

from openai import OpenAI
from dotenv import load_dotenv
import json

load_dotenv('.secrets')

client = OpenAI()

tools = [
    {
        "type": "function",
        "name": "get_horoscope",
        "description": "Get today's horoscope for an astrological sign.",
        "parameters": {
            "type": "object",
            "properties": {
                "sign": {
                    "type": "string",
                    "description": "An astrological sign like Taurus or Aquarius",
                },
            },
            "required": ["sign"],
        },
    },
]

def get_horoscope(sign):
    return f"{sign}: Next Tuesday you will befriend a baby otter."

input_list = [
    {"role": "user", "content": "What is the horoscope for Sagittarius?"}
]

response = client.responses.create(
    model="gpt-5", 
    tools = tools,
    input=input_list
)

input_list += response.output

for item in response.output:
    if item.type == "function_call":
        if item.name == "get_horoscope":
            args = json.loads(item.arguments)
            horoscope = get_horoscope(**args)

            input_list.append({
                "type": "function_call_output",
                "call_id": item.call_id,
                "output": json.dumps({
                    "horoscope": horoscope
                })
            })

print("Final input:")
print(input_list)

response = client.responses.create(
    model="gpt-5", 
    instructions="Respond only with a horoscope generated by a tool.",
    tools = tools,
    input=input_list
)

print("Final output:")
print(response.model_dump_json(indent=2))
print("\n" + response.output_text)